package genmonarch

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// generatedHeader marks the emitted TypeScript so nobody edits it by hand.
const generatedHeader = `// Code generated by cmd/genmonarch. DO NOT EDIT.
//
// Regenerate with: make monarch
// The tokenizers come from cel-go's CEL.g4 and text/template's lexer; the
// function catalogue is read from a live cel.Env and gomplate's FuncMap.
`

// Render turns a bundle into the files the npm package ships, keyed by
// filename. JSON is indented and newline-terminated so a regenerated tree
// produces a reviewable diff.
func Render(b *Bundle) (map[string][]byte, error) {
	files := map[string][]byte{}

	for _, id := range b.Order {
		lang := b.Languages[id]
		encoded, err := marshalIndent(lang)
		if err != nil {
			return nil, fmt.Errorf("%s tokenizer: %w", id, err)
		}
		files[id+".monarch.json"] = encoded

		encoded, err = marshalIndent(b.Configurations[id])
		if err != nil {
			return nil, fmt.Errorf("%s configuration: %w", id, err)
		}
		files[id+".config.json"] = encoded
	}

	spec, err := marshalIndent(b.Spec)
	if err != nil {
		return nil, fmt.Errorf("spec: %w", err)
	}
	files["spec.json"] = spec

	corpus, err := marshalIndent(b.Conformance)
	if err != nil {
		return nil, fmt.Errorf("conformance corpus: %w", err)
	}
	files["conformance.json"] = corpus

	files["index.ts"] = []byte(renderIndex(b))
	return files, nil
}

func marshalIndent(v any) ([]byte, error) {
	// Marshal first so the custom MarshalJSON methods run, then re-indent:
	// json.MarshalIndent does not indent the output of a custom marshaller.
	raw, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := json.Indent(&buf, raw, "", "  "); err != nil {
		return nil, err
	}
	buf.WriteByte('\n')
	return buf.Bytes(), nil
}

// renderIndex emits the typed entry point: every definition imported and keyed
// by language id, so the runtime package needs no per-language wiring.
func renderIndex(b *Bundle) string {
	var out strings.Builder
	out.WriteString(generatedHeader)
	out.WriteString("\nimport type { ConformanceCase, LanguageDefinition, GomplateSpec } from \"../types\";\n\n")

	ids := append([]string(nil), b.Order...)
	sort.Strings(ids)

	for _, id := range ids {
		symbol := identifierFor(id)
		fmt.Fprintf(&out, "import %sMonarch from \"./%s.monarch.json\";\n", symbol, id)
		fmt.Fprintf(&out, "import %sConfig from \"./%s.config.json\";\n", symbol, id)
	}
	out.WriteString("import specJson from \"./spec.json\";\n")
	out.WriteString("import conformanceJson from \"./conformance.json\";\n\n")

	out.WriteString("export const spec = specJson as GomplateSpec;\n\n")
	out.WriteString("/** Token boundaries produced by the languages' real lexers. */\n")
	out.WriteString("export const conformance = conformanceJson as ConformanceCase[];\n\n")

	out.WriteString("/** Every language id this package registers. */\n")
	out.WriteString("export const LANGUAGE_IDS = [\n")
	for _, id := range ids {
		fmt.Fprintf(&out, "  %q,\n", id)
	}
	out.WriteString("] as const;\n\n")
	out.WriteString("export type LanguageId = (typeof LANGUAGE_IDS)[number];\n\n")

	// The casts go through `unknown` because TypeScript widens a JSON import's
	// fixed-length arrays to `string[]`, while Monaco's types want tuples
	// (`CharacterPair`, `blockComment`). The shapes are produced by this
	// generator and covered by the tokenizer tests, so widening here loses
	// nothing that is actually checked elsewhere.
	out.WriteString("export const definitions: Record<LanguageId, LanguageDefinition> = {\n")
	for _, id := range ids {
		symbol := identifierFor(id)
		fmt.Fprintf(&out, "  %q: {\n    id: %q,\n    monarch: %sMonarch as unknown as LanguageDefinition[\"monarch\"],\n    configuration: %sConfig as unknown as LanguageDefinition[\"configuration\"],\n  },\n",
			id, id, symbol, symbol)
	}
	out.WriteString("};\n")
	return out.String()
}

// identifierFor turns a language id into a JS identifier: `yaml-gomplate` ->
// `yamlGomplate`.
func identifierFor(id string) string {
	parts := strings.Split(id, "-")
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}
