package genmonarch

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// generatedHeader marks the emitted TypeScript so nobody edits it by hand.
const generatedHeader = `// Code generated by cmd/genmonarch. DO NOT EDIT.
//
// Regenerate with: make monarch
// The tokenizers come from cel-go's CEL.g4 and text/template's lexer; the
// function catalogue is read from a live cel.Env and gomplate's FuncMap.
`

// languageDefinition is one language's whole editor contract -- tokenizer plus
// configuration -- in the shape the npm package's LanguageDefinition declares.
// Every language ships in a single generated file rather than two files each:
// the consumer always loads the whole set, and one artifact keeps the generated
// tree small enough to review.
type languageDefinition struct {
	ID            string        `json:"id"`
	Monarch       Language      `json:"monarch"`
	Configuration Configuration `json:"configuration"`
}

// Render turns a bundle into the files the npm package ships, keyed by
// filename. JSON is indented and newline-terminated so a regenerated tree
// produces a reviewable diff.
func Render(b *Bundle) (map[string][]byte, error) {
	files := map[string][]byte{}

	// Keyed by language id: encoding/json sorts map keys, so the file is stable
	// regardless of the order languages were built in.
	definitions := make(map[string]languageDefinition, len(b.Order))
	for _, id := range b.Order {
		definitions[id] = languageDefinition{
			ID:            id,
			Monarch:       b.Languages[id],
			Configuration: b.Configurations[id],
		}
	}
	languages, err := marshalIndent(definitions)
	if err != nil {
		return nil, fmt.Errorf("language definitions: %w", err)
	}
	files["languages.json"] = languages

	spec, err := marshalIndent(b.Spec)
	if err != nil {
		return nil, fmt.Errorf("spec: %w", err)
	}
	files["spec.json"] = spec

	corpus, err := marshalIndent(b.Conformance)
	if err != nil {
		return nil, fmt.Errorf("conformance corpus: %w", err)
	}
	files["conformance.json"] = corpus

	files["index.ts"] = []byte(renderIndex(b))
	return files, nil
}

func marshalIndent(v any) ([]byte, error) {
	// Marshal first so the custom MarshalJSON methods run, then re-indent:
	// json.MarshalIndent does not indent the output of a custom marshaller.
	raw, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := json.Indent(&buf, raw, "", "  "); err != nil {
		return nil, err
	}
	buf.WriteByte('\n')
	return buf.Bytes(), nil
}

// renderIndex emits the typed entry point: every definition imported and keyed
// by language id, so the runtime package needs no per-language wiring.
func renderIndex(b *Bundle) string {
	var out strings.Builder
	out.WriteString(generatedHeader)
	out.WriteString("\nimport type { ConformanceCase, LanguageDefinition, GomplateSpec } from \"../types\";\n\n")

	ids := append([]string(nil), b.Order...)
	sort.Strings(ids)

	out.WriteString("import languagesJson from \"./languages.json\";\n")
	out.WriteString("import specJson from \"./spec.json\";\n")
	out.WriteString("import conformanceJson from \"./conformance.json\";\n\n")

	out.WriteString("export const spec = specJson as GomplateSpec;\n\n")
	out.WriteString("/** Token boundaries produced by the languages' real lexers. */\n")
	out.WriteString("export const conformance = conformanceJson as ConformanceCase[];\n\n")

	out.WriteString("/** Every language id this package registers. */\n")
	out.WriteString("export const LANGUAGE_IDS = [\n")
	for _, id := range ids {
		fmt.Fprintf(&out, "  %q,\n", id)
	}
	out.WriteString("] as const;\n\n")
	out.WriteString("export type LanguageId = (typeof LANGUAGE_IDS)[number];\n\n")

	// The cast goes through `unknown` because TypeScript widens a JSON import's
	// fixed-length arrays to `string[]`, while Monaco's types want tuples
	// (`CharacterPair`, `blockComment`). The shapes are produced by this
	// generator and covered by the tokenizer tests, so widening here loses
	// nothing that is actually checked elsewhere.
	out.WriteString("export const definitions = languagesJson as unknown as Record<LanguageId, LanguageDefinition>;\n")
	return out.String()
}
