linters-settings:
  govet:
    check-shadowing: true
    disable:
      # printf: non-constant format string in call to fmt.Errorf (govet)
      # showing up since golangci-lint version 1.60.1
      - printf
    # enable:
      # - fieldalignment FIXME:
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  gocritic:
    disabled-checks:
      - singleCaseSwitch # FIXME:
  goconst:
    min-len: 2
    min-occurrences: 4
  staticcheck:
    go: "1.20"
    checks:
      - "all"
      - "-SA1019"
  lll:
    line-length: 140
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    # - deadcode FIXME:
    # - depguard FIXME:
    # - dogsled
    # - dupl
    # - errcheck
    # - exhaustive
    - exportloopref
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    # - godox
    - gofmt
    # - gofumpt
    - goheader
    # - goimports FIXME:
    # - gomnd
    - gomodguard
    - goprintffuncname
    # - gosec FIXME:
    - gosimple
    # - govet FIXME:
    - ineffassign
    # - lll
    - misspell
    - nakedret
    # - nestif
    # - nlreturn
    # - noctx
    # - nolintlint
    - prealloc
    # - revive FIXME:
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - structcheck #  This linter is fully inactivated: it will not produce any reports.
    - stylecheck
    - typecheck
    - unconvert
    # - unparam
    # - unused FIXME:
    # - varcheck  #  This linter is fully inactivated: it will not produce any reports.
    # - whitespace
    # - wsl

run:
  concurrency: 4
  timeout: 5m
