version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - goconst
    - gocritic
    - goheader
    - gomodguard
    - goprintffuncname
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gocyclo:
      min-complexity: 10
    govet:
      disable:
        - printf
    lll:
      line-length: 140
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
