import type * as monaco from "monaco-editor";

/** The subset of the Monaco namespace this package needs. */
export type Monaco = typeof monaco;

/** One generated language: its tokenizer and its editor configuration. */
export interface LanguageDefinition {
  id: string;
  monarch: monaco.languages.IMonarchLanguage;
  configuration: monaco.languages.LanguageConfiguration;
}

/** One typed signature of a CEL function. */
export interface Overload {
  id: string;
  args: string[];
  result: string;
  member?: boolean;
}

/** A callable name, with every registered overload. */
export interface SpecFunction {
  name: string;
  namespace?: string;
  /** Callable only as `x.f()`, never as `f(x)`. */
  memberOnly?: boolean;
  doc?: string;
  /** Go signature; go-template functions only. */
  signature?: string;
  overloads?: Overload[];
  examples?: string[];
}

/** A CEL macro. Expanded at parse time, so never a function. */
export interface SpecMacro {
  name: string;
  argCount: number;
  receiverStyle: boolean;
  doc?: string;
  examples?: string[];
}

export interface CelSpec {
  namespaces: string[];
  keywords: string[];
  types: string[];
  variables?: string[];
  macros: SpecMacro[];
  functions: SpecFunction[];
}

export interface Delimiters {
  left: string;
  right: string;
  leftComment: string;
  rightComment: string;
  trimMarker: string;
}

export interface GoTemplateSpec {
  namespaces: string[];
  keywords: string[];
  builtins: string[];
  delimiters: Delimiters;
  functions: SpecFunction[];
}

/** The full catalogue, generated from gomplate's own registries. */
export interface GomplateSpec {
  cel: CelSpec;
  gotemplate: GoTemplateSpec;
}

/**
 * One snippet plus the token boundaries the language's real lexer produces.
 *
 * Generated by running cel-go's own ANTLR lexer over the snippet, so the
 * tokenizer is checked against the parser gomplate evaluates with rather than
 * against a snapshot of its own output. Snippets for languages whose lexer is
 * not reachable carry no boundaries; they are validated by their real parser at
 * generation time and only smoke-tested here.
 */
export interface ConformanceCase {
  language: string;
  source: string;
  /** 0-based offsets where a token starts, whitespace excluded. */
  boundaries?: number[];
  /** Where the snippet came from, so a failure is traceable. */
  origin: string;
}
