// Code generated by "gencel";
// DO NOT EDIT.

package funcs

import "github.com/google/cel-go/common/types"
import "github.com/google/cel-go/cel"
import "github.com/google/cel-go/common/types/ref"

var EC2TagsawsGen = cel.Function("EC2Tags",
	cel.Overload("EC2Tags_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x Funcs
			a0, a1 := x.EC2Tags()
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var KMSEncryptawsGen = cel.Function("KMSEncrypt",
	cel.Overload("KMSEncrypt_interface{}_interface{}",

		[]*cel.Type{
			cel.DynType, cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x Funcs
			a0, a1 := x.KMSEncrypt(args[0], args[1])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var KMSDecryptawsGen = cel.Function("KMSDecrypt",
	cel.Overload("KMSDecrypt_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x Funcs
			a0, a1 := x.KMSDecrypt(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var UserIDawsGen = cel.Function("UserID",
	cel.Overload("UserID_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x Funcs
			a0, a1 := x.UserID()
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var AccountawsGen = cel.Function("Account",
	cel.Overload("Account_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x Funcs
			a0, a1 := x.Account()
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var ARNawsGen = cel.Function("ARN",
	cel.Overload("ARN_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x Funcs
			a0, a1 := x.ARN()
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)
