// Code generated by gencel. DO NOT EDIT.

package funcs

import "github.com/google/cel-go/cel"
import "github.com/google/cel-go/common/types"
import "github.com/google/cel-go/common/types/ref"

var k8sIsHealthyGen = cel.Function("IsHealthy",
	cel.Overload("IsHealthy_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.BoolType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x KubernetesFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.IsHealthy(args[0]))

		}),
	),
)

var k8sIsReadyGen = cel.Function("IsReady",
	cel.Overload("IsReady_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.BoolType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x KubernetesFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.IsReady(args[0]))

		}),
	),
)

var k8sGetStatusGen = cel.Function("GetStatus",
	cel.Overload("GetStatus_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.StringType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x KubernetesFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.GetStatus(args[0]))

		}),
	),
)

var k8sGetHealthGen = cel.Function("GetHealth",
	cel.Overload("GetHealth_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x KubernetesFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.GetHealth(args[0]))

		}),
	),
)

var k8sGetHealthMapGen = cel.Function("GetHealthMap",
	cel.Overload("GetHealthMap_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x KubernetesFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.GetHealthMap(args[0]))

		}),
	),
)

var k8sNeatGen = cel.Function("Neat",
	cel.Overload("Neat_string",

		[]*cel.Type{
			cel.StringType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x KubernetesFuncs

			a0, a1 := x.Neat(args[0].Value().(string))
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)
