// Code generated by "gencel";
// DO NOT EDIT.

package funcs

import "github.com/google/cel-go/common/types"
import "github.com/google/cel-go/cel"
import "github.com/google/cel-go/common/types/ref"

var TernarytestGen = cel.Function("test.Ternary",
	cel.Overload("test.Ternary_interface{}_interface{}_interface{}",

		[]*cel.Type{
			cel.DynType, cel.DynType, cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TestFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.Ternary(args[0], args[1], args[2]))

		}),
	),
)

var KindtestGen = cel.Function("test.Kind",
	cel.Overload("test.Kind_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.StringType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TestFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.Kind(args[0]))

		}),
	),
)

var IsKindtestGen = cel.Function("test.IsKind",
	cel.Overload("test.IsKind_string_interface{}",

		[]*cel.Type{
			cel.StringType, cel.DynType,
		},
		cel.BoolType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TestFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.IsKind(args[0].Value().(string), args[1]))

		}),
	),
)
