// Code generated by "gencel";
// DO NOT EDIT.

package funcs

import "github.com/google/cel-go/common/types"
import "github.com/google/cel-go/cel"
import "github.com/google/cel-go/common/types/ref"

var ZoneNametimeGen = cel.Function("ZoneName",
	cel.Overload("ZoneName_",
		nil,
		cel.StringType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.ZoneName())

		}),
	),
)

var ZoneOffsettimeGen = cel.Function("ZoneOffset",
	cel.Overload("ZoneOffset_",
		nil,
		cel.IntType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.DefaultTypeAdapter.NativeToValue(x.ZoneOffset())

		}),
	),
)

var ParsetimeGen = cel.Function("Parse",
	cel.Overload("Parse_string_interface{}",

		[]*cel.Type{
			cel.StringType, cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs
			a0, a1 := x.Parse(args[0].Value().(string), args[1])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var ParseLocaltimeGen = cel.Function("ParseLocal",
	cel.Overload("ParseLocal_string_interface{}",

		[]*cel.Type{
			cel.StringType, cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs
			a0, a1 := x.ParseLocal(args[0].Value().(string), args[1])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var ParseInLocationtimeGen = cel.Function("ParseInLocation",
	cel.Overload("ParseInLocation_string_string_interface{}",

		[]*cel.Type{
			cel.StringType, cel.StringType, cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs
			a0, a1 := x.ParseInLocation(args[0].Value().(string), args[1].Value().(string), args[2])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var NowtimeGen = cel.Function("Now",
	cel.Overload("Now_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Timestamp{Time: x.Now()}

		}),
	),
)

var UnixtimeGen = cel.Function("Unix",
	cel.Overload("Unix_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs
			a0, a1 := x.Unix(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var NanosecondtimeGen = cel.Function("Nanosecond",
	cel.Overload("Nanosecond_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Nanosecond(args[0])}

		}),
	),
)

var MicrosecondtimeGen = cel.Function("Microsecond",
	cel.Overload("Microsecond_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Microsecond(args[0])}

		}),
	),
)

var MillisecondtimeGen = cel.Function("Millisecond",
	cel.Overload("Millisecond_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Millisecond(args[0])}

		}),
	),
)

var SecondtimeGen = cel.Function("Second",
	cel.Overload("Second_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Second(args[0])}

		}),
	),
)

var MinutetimeGen = cel.Function("Minute",
	cel.Overload("Minute_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Minute(args[0])}

		}),
	),
)

var HourtimeGen = cel.Function("Hour",
	cel.Overload("Hour_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Hour(args[0])}

		}),
	),
)

var ParseDurationtimeGen = cel.Function("ParseDuration",
	cel.Overload("ParseDuration_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs
			a0, a1 := x.ParseDuration(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var SincetimeGen = cel.Function("Since",
	cel.Overload("Since_time.Time",

		[]*cel.Type{
			cel.TimestampType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Since(args[0].Value().(time.Time))}

		}),
	),
)

var UntiltimeGen = cel.Function("Until",
	cel.Overload("Until_time.Time",

		[]*cel.Type{
			cel.TimestampType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x TimeFuncs

			return types.Duration{Duration: x.Until(args[0].Value().(time.Time))}

		}),
	),
)
